### ISSUE TITLE
Repeated solutions, Constrained Problem

### ISSUE THREAD

**Issue by ghost** [tichugh/K-RVEA#1]
1. How do you handle the case when the solutions returned by evolve_K_RVEA() (line 63 of Main) are same as previously found in 'Population'? What is 'PS' in line 71?
2. Can this algorithm run for constrained multi-objective problems? How do you model constraints?
3. Only two solutions are returned by  evolve_K_RVEA() , is it standard or it can be changed?

**Comment by tichugh** [comment]
1. "PS" is same as "Population", it was a typo. I replaced "PS" with "Population". If samples are same, I run the RVEA again with surrogates to make sure that they are different from previously evaluated samples (Lines 64 - 79).

2.  This code cannot handle constraints. I will make a repository for the cK-RVEA developed to handle constraints. 

3. You can change the number in evolve_K_RVEA. It is defined as "up_var". 

Hope this helps.

**Comment by ghost** [comment]
Thank you for your answer. Do you have any recommendations for "up_var"? Or we can just use default=M. What was the value of "up_var" in your TEVC paper?

**Comment by tichugh** [comment]
Hi, for recommendations and the literature for this parameter, I would suggest to see the Survey on the topic: Chugh, T., Sindhya, K., Hakanen, J. et al. A survey on handling computationally expensive multiobjective optimization problems with evolutionary algorithms. Soft Computing (2017). https://doi.org/10.1007/s00500-017-2965-0
I used five in K-RVEA which is published in TEVC.
